name: Build PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          output/cv.pdf
        key: ${{ hashFiles('**') }}
    - uses: Tommoa/tectonic-fontawesome-action@v0.5
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        tex_path: main.tex
    - name: Rename
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          mkdir -p output
          mv main.pdf output/cv.pdf
    - uses: actions/upload-artifact@v1
      with:
        name: cv.pdf
        path: output/cv.pdf
    - name: Deploy to GitHub Pages
      if: steps.cache.outputs.cache-hit != 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./output
        allow_empty_commit: false
        publish_branch: rendered
