name: Build PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install FontAwesome
      run: sudo apt install fonts-font-awesome
    - name: Download Tectonic
      run: cargo install tectonic
    - name: Build
      run: tectonic main.tex
    - uses: actions/upload-artifact@v1
      with:
        name: CV.pdf
        path: main.pdf
