name: Build PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install FontAwesome
      run: sudo apt install fonts-font-awesome
    - name: Download Tectonic
      run: cargo install tectonic
    - name: Build
      run: |
          tectonic main.tex
          mv main.pdf CV.pdf
    - uses: actions/upload-artifact@v1
      with:
        name: CV.pdf
        path: CV.pdf
    - name: Deploy to gh-pages branch
      uses: docker://peaceiris/gh-pages:latest
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
      with:
        emptyCommits: false
